- name: Playbook to Install and Configure Tools for Jenkins Agent
  hosts: all
  become: yes
  vars:
    user_name: ubuntu  # Change this to the user you want to add to the docker group

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install Required packages
      apt:
        name:
          - openjdk-17-jre
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      notify: restart docker

    - name: Add user to Docker group
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: Check if SonarQube container is already present
      docker_container_info:
        name: sonar
      register: sonar_container_info

    - name: Run SonarQube container
      docker_container:
        name: sonar
        image: sonarqube:lts-community
        ports:
          - "9000:9000"
        state: started
        restart_policy: always
      when: not sonar_container_info.exists

    - name: Add Trivy GPG key and repository
      shell:
        cmd: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/trivy.list
        executable: /bin/bash
      args:
        creates: /etc/apt/sources.list.d/trivy.list

    - name: Install Trivy dependencies
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        state: present

    - name: Install Trivy
      apt:
        name: trivy
        update_cache: yes
        state: present
    
    - name: Install Snyk
      shell: curl -fsSL https://static.snyk.io/cli/latest/snyk-linux -o /usr/local/bin/snyk && chmod +x /usr/local/bin/snyk
      args:
        creates: /usr/local/bin/snyk

    - name: Install kubectl
      shell: |
        KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        curl -fsSL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
        chmod +x /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install AWS CLI dependencies
      apt:
        name: unzip
        state: present

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
        unzip -q /tmp/awscliv2.zip -d /tmp
        /tmp/aws/install
        rm -rf /tmp/aws /tmp/awscliv2.zip
      args:
        creates: /usr/local/bin/aws
    
    - name: Install Helm
      shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
      args:
        creates: /usr/local/bin/helm

  handlers:
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
