- name: Playbook to Install Jenkins
  hosts: all
  become: yes

  tasks:
    - name: Import and add Jenkins repository
      shell:
        cmd: |
          wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
        executable: /bin/bash
      args:
        creates: /etc/apt/sources.list.d/jenkins.list

    - name: Install required packages
      apt:
        name:
          - openjdk-17-jre
        state: present
        update_cache: yes

    - name: Install Jenkins latest version
      apt:
        name: jenkins
        state: present
        update_cache: yes